version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=America/Los_Angeles
    restart: always
    # Running with network_mode: host seems to be necessary to in order for
    # discovery and bluetooth? Not sure if we'll be using those things...
    # Some discussion about this over here:
    #  https://community.home-assistant.io/t/avoid-network-mode-host-for-docker/47250
    #network_mode: host

    ports:
      - "8123:8123"
