#!/bin/sh

set -e

base_domain=clark.snowdon.jflei.com
export LE_FQDN=$(cat /etc/nginx/service-htpc.conf | grep -o '[^ ]*\.\*' | grep -v '~\^\.\*'| sed "s_*_${base_domain}_" | sort -u | paste -s -d, -)
export LE_FQDN="${base_domain},$LE_FQDN"

echo "Autogenerated LE_FQDN by parsing /etc/nginx/service-htpc.conf: $LE_FQDN"

exec /entrypoint.sh
