# Copied from https://github.com/umputun/nginx-le

version: '2'
services:
    nginx:
        build: .
        hostname: nginx
        restart: always
        container_name: nginx
        # In order for proxy_pass to other services running on this server to
        # work, we need to run in "host" network mode.
        network_mode: host

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - /etc/clark/nginx/ssl:/etc/nginx/ssl
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/service-htpc.conf:/etc/nginx/service-htpc.conf
            - /mnt/media/.build-secrets/htpc-ui/auth:/etc/nginx/auth
            - ./webroot:/webroot
            - /mnt/media:/mnt/media

        environment:
            - TZ=America/Los_Angeles
            - LETSENCRYPT=true
            - LE_EMAIL=jeremyfleischman@gmail.com
            # Note: No need to set LE_FQDN because we're doing something
            # clever. See our Dockerfile and the autogen-lefqdn-entrypoint.sh
            # script.
