# Copied from https://github.com/umputun/nginx-le

version: '2'
services:
    nginx:
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx
        # In order for proxy_pass to other services running on this server to
        # work, we need to run in "host" network mode.
        network_mode: host

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - /etc/clark/nginx/ssl:/etc/nginx/ssl
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/htpc.conf:/etc/nginx/service-htpc.conf
            - ./etc/nginx/basic_auth_file:/etc/nginx/basic_auth_file
            - ./webroot:/webroot
            - /mnt/media:/mnt/media

        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=America/Los_Angeles
            - LETSENCRYPT=true
            - LE_EMAIL=jeremyfleischma@gmail.com
            - LE_FQDN=clark.jflei.com,kodi.clark.jflei.com,sync.clark.jflei.com,media.clark.jflei.com,torrents.clark.jflei.com,cups.clark.jflei.com,roomba.clark.jflei.com,home-assistant.clark.jflei.com
