live_config_reload: true

env:
  TERM: xterm-256color

font:
  normal:
    family: monospace

  # Monitor
  size: 8.0
  # Mobile
  #<<< size: 11.0

schemes:
    solarized_light: &solarized_light
      primary:
        background: '#fdf6e3' # base3
        foreground: '#657b83' # base00
      cursor:
        text:   '#fdf6e3' # base3
        cursor: '#657b83' # base00
      normal:
        black:   '#073642' # base02
        red:     '#dc322f' # red
        green:   '#859900' # green
        yellow:  '#b58900' # yellow
        blue:    '#268bd2' # blue
        magenta: '#d33682' # magenta
        cyan:    '#2aa198' # cyan
        white:   '#eee8d5' # base2
      bright:
        black:   '#002b36' # base03
        red:     '#cb4b16' # orange
        green:   '#586e75' # base01
        yellow:  '#657b83' # base00
        blue:    '#839496' # base0
        magenta: '#6c71c4' # violet
        cyan:    '#93a1a1' # base1
        white:   '#fdf6e3' # base3

    solarized_dark: &solarized_dark
      primary:
        background: '#002b36' # base03
        foreground: '#839496' # base0
      cursor:
        text:   '#002b36' # base03
        cursor: '#839496' # base0
      normal:
        black:   '#073642' # base02
        red:     '#dc322f' # red
        green:   '#859900' # green
        yellow:  '#b58900' # yellow
        blue:    '#268bd2' # blue
        magenta: '#d33682' # magenta
        cyan:    '#2aa198' # cyan
        white:   '#eee8d5' # base2
      bright:
        black:   '#002b36' # base03
        red:     '#cb4b16' # orange
        green:   '#586e75' # base01
        yellow:  '#657b83' # base00
        blue:    '#839496' # base0
        magenta: '#6c71c4' # violet
        cyan:    '#93a1a1' # base1
        white:   '#fdf6e3' # base3

    base16_solarized_dark: &base16_solarized_dark
      # Default colors
      primary:
        background: '0x002b36'
        foreground: '0x93a1a1'

      # Colors the cursor will use if `custom_cursor_colors` is true
      cursor:
        text: '0x002b36'
        cursor: '0x93a1a1'

      # Normal colors
      normal:
        black:   '0x002b36'
        red:     '0xdc322f'
        green:   '0x859900'
        yellow:  '0xb58900'
        blue:    '0x268bd2'
        magenta: '0x6c71c4'
        cyan:    '0x2aa198'
        white:   '0x93a1a1'

      # Bright colors
      bright:
        black:   '0x657b83'
        red:     '0xcb4b16'
        green:   '0x073642'
        yellow:  '0x586e75'
        blue:    '0x839496'
        magenta: '0xeee8d5'
        cyan:    '0xd33682'
        white:   '0xfdf6e3'

    base16_solarized_light: &base16_solarized_light
      # Default colors
      primary:
        background: '0xfdf6e3'
        foreground: '0x586e75'

      # Colors the cursor will use if `custom_cursor_colors` is true
      cursor:
        text: '0xfdf6e3'
        cursor: '0x586e75'

      # Normal colors
      normal:
        black:   '0xfdf6e3'
        red:     '0xdc322f'
        green:   '0x859900'
        yellow:  '0xb58900'
        blue:    '0x268bd2'
        magenta: '0x6c71c4'
        cyan:    '0x2aa198'
        white:   '0x586e75'

      # Bright colors
      bright:
        black:   '0x839496'
        red:     '0xcb4b16'
        green:   '0xeee8d5'
        yellow:  '0x93a1a1'
        blue:    '0x657b83'
        magenta: '0x073642'
        cyan:    '0xd33682'
        white:   '0x002b36'

    tango_light: &tango_light
      bright:
        black: '#555753'
        blue: '#729fcf'
        cyan: '#34e2e2'
        green: '#8ae234'
        magenta: '#ad7fa8'
        red: '#ef2929'
        white: '#eeeeec'
        yellow: '#fce94f'
      cursor:
        cursor: '#000000'
        text: '#ffffff'
      normal:
        black: '#000000'
        blue: '#3465a4'
        cyan: '#06989a'
        green: '#4e9a06'
        magenta: '#75507b'
        red: '#cc0000'
        white: '#d3d7cf'
        yellow: '#c4a000'
      primary:
        background: '#ffffff'
        foreground: '#000000'
      selection:
        background: '#b5d5ff'
        text: '#000000'
    tango_dark: &tango_dark
      bright:
        black: '#555753'
        blue: '#729fcf'
        cyan: '#34e2e2'
        green: '#8ae234'
        magenta: '#ad7fa8'
        red: '#ef2929'
        white: '#eeeeec'
        yellow: '#fce94f'
      cursor:
        cursor: '#ffffff'
        text: '#000000'
      normal:
        black: '#000000'
        blue: '#3465a4'
        cyan: '#06989a'
        green: '#4e9a06'
        magenta: '#75507b'
        red: '#cc0000'
        white: '#d3d7cf'
        yellow: '#c4a000'
      primary:
        background: '#000000'
        foreground: '#ffffff'
      selection:
        background: '#b5d5ff'
        text: '#000000'

    nord: &nord
      primary:
        background: '#2e3440'
        foreground: '#d8dee9'
        dim_foreground: '#a5abb6'
      cursor:
        text: '#2e3440'
        cursor: '#d8dee9'
      vi_mode_cursor:
        text: '#2e3440'
        cursor: '#d8dee9'
      selection:
        text: CellForeground
        background: '#4c566a'
      search:
        matches:
          foreground: CellBackground
          background: '#88c0d0'
        bar:
          background: '#434c5e'
          foreground: '#d8dee9'
      normal:
        black: '#3b4252'
        red: '#bf616a'
        green: '#a3be8c'
        yellow: '#ebcb8b'
        blue: '#81a1c1'
        magenta: '#b48ead'
        cyan: '#88c0d0'
        white: '#e5e9f0'
      bright:
        black: '#4c566a'
        red: '#bf616a'
        green: '#a3be8c'
        yellow: '#ebcb8b'
        blue: '#81a1c1'
        magenta: '#b48ead'
        cyan: '#8fbcbb'
        white: '#eceff4'
      dim:
        black: '#373e4d'
        red: '#94545d'
        green: '#809575'
        yellow: '#b29e75'
        blue: '#68809a'
        magenta: '#8c738c'
        cyan: '#6d96a5'
        white: '#aeb3bb'

    selenized_black: &selenized_black
      primary:
        background: '0x181818'
        foreground: '0xb9b9b9'
      normal:
        black:   '0x252525'
        red:     '0xed4a46'
        green:   '0x70b433'
        yellow:  '0xdbb32d'
        blue:    '0x368aeb'
        magenta: '0xeb6eb7'
        cyan:    '0x3fc5b7'
        white:   '0x777777'
      bright:
        black:   '0x3b3b3b'
        red:     '0xff5e56'
        green:   '0x83c746'
        yellow:  '0xefc541'
        blue:    '0x4f9cfe'
        magenta: '0xff81ca'
        cyan:    '0x56d8c9'
        white:   '0xdedede'

    selenized_dark: &selenized_dark
      primary:
        background: '0x103c48'
        foreground: '0xadbcbc'
      normal:
        black:   '0x184956'
        red:     '0xfa5750'
        green:   '0x75b938'
        yellow:  '0xdbb32d'
        blue:    '0x4695f7'
        magenta: '0xf275be'
        cyan:    '0x41c7b9'
        white:   '0x72898f'
      bright:
        black:   '0x2d5b69'
        red:     '0xff665c'
        green:   '0x84c747'
        yellow:  '0xebc13d'
        blue:    '0x58a3ff'
        magenta: '0xff84cd'
        cyan:    '0x53d6c7'
        white:   '0xcad8d9'

    selenized_light: &selenized_light
      primary:
        background: '0xfbf3db'
        foreground: '0x53676d'
      normal:
        black:   '0xece3cc'
        red:     '0xd2212d'
        green:   '0x489100'
        yellow:  '0xad8900'
        blue:    '0x0072d4'
        magenta: '0xca4898'
        cyan:    '0x009c8f'
        white:   '0x909995'
      bright:
        black:   '0xd5cdb6'
        red:     '0xcc1729'
        green:   '0x428b00'
        yellow:  '0xa78300'
        blue:    '0x006dce'
        magenta: '0xc44392'
        cyan:    '0x00978a'
        white:   '0x3a4d53'

    selenized_white: &selenized_white
      primary:
        background: '0xffffff'
        foreground: '0x474747'
      normal:
        black:   '0xebebeb'
        red:     '0xd6000c'
        green:   '0x1d9700'
        yellow:  '0xc49700'
        blue:    '0x0064e4'
        magenta: '0xdd0f9d'
        cyan:    '0x00ad9c'
        white:   '0x878787'
      bright:
        black:   '0xcdcdcd'
        red:     '0xbf0000'
        green:   '0x008400'
        yellow:  '0xaf8500'
        blue:    '0x0054cf'
        magenta: '0xc7008b'
        cyan:    '0x009a8a'
        white:   '0x282828'

#<<< colors: *solarized_light
#<<< colors: *solarized_dark
#<<< colors: *base16_solarized_dark
#<<< colors: *base16_solarized_light
#<<< colors: *tango_light
#<<< colors: *nord
#<<< colors: *selenized_black
#<<< colors: *selenized_white
#<<< colors: *selenized_light
colors: *selenized_dark
