### Dead simple prompt for demos
export PS1="$ "
export SHELL="bash"
##################################

export HISTCONTROL=ignorespace

# Set up FZF (https://wiki.archlinux.org/index.php/Fzf#bash)
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

# Better dircolors for solarized
# http://archlinux.me/w0ng/2012/04/21/better-dircolors-with-solarized/
eval $(dircolors ~/.dir_colors)

# Lower probability of weird line wrapping issues
# https://wiki.archlinux.org/index.php/bash#Line_wrap_on_window_resize
shopt -s checkwinsize
