# Start with a fresh PATH.
export PATH=""

source ~/.commonrc/path.sh

###
### Workaround for that ridiculous Java bug on xmonad
### https://wiki.archlinux.org/index.php/Java#Applications_not_resizing_with_WM.2C_menus_immediately_closing
###
export _JAVA_AWT_WM_NONREPARENTING=1

# startx at login
[[ -z $DISPLAY && $XDG_VTNR -eq 1 && -z $TMUX ]] && exec startx
