# TODO: remove this once we're no longer using dotbot to manage these files
cat > "$(CreateFile /etc/systemd/system/systemd-logind.service.d/override.conf)" <<EOF
[Service]
# Allow symlinks into the home directory.
ProtectHome=no
EOF

# TODO: stop managing these with dotbot
# This list generated by running `grep dotfiles 99-unsorted.sh`
CreateLink /etc/acpi/events/cd_play /home/jeremy/gitting/dotfiles/etc/acpi/events/cd_play
CreateLink /etc/acpi/events/lid /home/jeremy/gitting/dotfiles/etc/acpi/events/lid
CreateLink /etc/modprobe.d/nobeep.conf /home/jeremy/gitting/dotfiles/etc/modprobe.d/nobeep.conf
CreateLink /etc/systemd/logind.conf.d/no-suspend-on-lidswitch.conf /home/jeremy/gitting/dotfiles/etc/systemd/logind.conf.d/no-suspend-on-lidswitch.conf
CreateLink /etc/systemd/logind.conf.d/suspend-on-powerbutton.conf /home/jeremy/gitting/dotfiles/etc/systemd/logind.conf.d/suspend-on-powerbutton.conf
CreateLink /etc/systemd/system/disable-bt-wakeup.service /home/jeremy/gitting/dotfiles/etc/systemd/system/disable-bt-wakeup.service
CreateLink /etc/systemd/system/fixinputs.path /home/jeremy/gitting/dotfiles/units/fixinputs.path
CreateLink /etc/systemd/system/fixinputs.service /home/jeremy/gitting/dotfiles/units/fixinputs.service
CreateLink /etc/systemd/system/fixinputs@.path /home/jeremy/gitting/dotfiles/etc/systemd/system/fixinputs@.path
CreateLink /etc/systemd/system/fixinputs@.service /home/jeremy/gitting/dotfiles/etc/systemd/system/fixinputs@.service
CreateLink /etc/systemd/system/fixinputs@jeremy.path /home/jeremy/gitting/dotfiles/etc/systemd/system/fixinputs@.path
CreateLink /etc/systemd/system/monitors@.service /home/jeremy/gitting/dotfiles/etc/systemd/system/monitors@.service
CreateLink /etc/systemd/system/multi-user.target.wants/disable-bt-wakeup.service /home/jeremy/gitting/dotfiles/etc/systemd/system//disable-bt-wakeup.service
CreateLink /etc/systemd/system/multi-user.target.wants/fixinputs@jeremy.path /home/jeremy/gitting/dotfiles/etc/systemd/system/fixinputs@.path
CreateLink /etc/systemd/system/sleep.target.wants/slock@jeremy.service /home/jeremy/gitting/dotfiles/etc/systemd/system/slock@.service
CreateLink /etc/systemd/system/slock@.service /home/jeremy/gitting/dotfiles/etc/systemd/system/slock@.service
CreateLink /etc/systemd/system/slock@jeremy.service /home/jeremy/gitting/dotfiles/etc/systemd/system/slock@.service
CreateLink /etc/udev/rules.d/10-local.rules /home/jeremy/gitting/dotfiles/etc/udev/rules.d/10-local.rules
CreateLink /etc/udevmon.yaml /home/jeremy/gitting/dotfiles/etc/udevmon.yaml
CreateLink /usr/lib/systemd/system/monitors.service /home/jeremy/gitting/dotfiles/units/monitors.service
