# TODO: remove this once we're no longer using dotbot to manage these files
cat > "$(CreateFile /etc/systemd/system/systemd-logind.service.d/override.conf)" <<EOF
[Service]
# Allow symlinks into the home directory.
ProtectHome=no
EOF

# TODO: stop managing these with dotbot
# This list generated by running `grep dotfiles 99-unsorted.sh`
CreateLink /etc/systemd/system/disable-bt-wakeup.service /home/jeremy/gitting/dotfiles/etc/systemd/system/disable-bt-wakeup.service
CreateLink /etc/systemd/system/multi-user.target.wants/disable-bt-wakeup.service /home/jeremy/gitting/dotfiles/etc/systemd/system//disable-bt-wakeup.service
